spring:
  application:
    name: servicio-oauth
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 9100
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.formacionbdi.springboot.app: debug