spring:
  application:
    name: servicio-oauth
    #Se modifica la probabilidad en que Sleuth va a enviar las trazas a Zipkin, por defecto sólo se envian el 10% de las veces (request)
#0.1 es el 10% y 1 es el 100% de las veces
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 9100
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
logging:
  level:
    com.formacionbdi.springboot.app: debug